### ISSUE TITLE
Exec don't initiate

### ISSUE THREAD

**Issue by morcegon** [Scandit/BarcodeScannerPlugin#22]
Hello!

I've followed the instructions, but when I press the scan button, nothing happen. I to put a log on scan function. The log is printed on console, but the cordova.exec don't return any result.
Do you can help me?

Thanks.

**Comment by moritz-scandit** [comment]
Hi, do you see any kind of error message? if cordova.exec() is executed it should either open the scanner or tell you that it can't find the plugin (because it is not defined properly).

**Comment by morcegon** [comment]
No, I can't see any errors.
I've tested my app with the Phonegap camera plugin and it's works fine. But, when I test with Scandit, nothing's happen.

**Comment by moritz-scandit** [comment]
I can offer you to look at the project (or a minimal version of it) if you send it to info@scandit.com. Other than that there is not much I can do since there is no obvious error case where it simply doesn't work without an error.

**Comment by hbi99** [comment]
+1
same here...nothing happens when I click the "scan" button.
No errors

**Comment by moritz-scandit** [comment]
As I wrote in my previous replies, there should be some kind of error poping up in the console log if cordova.exec doesn't do anything. And as I said before there is no obvious error case where it simply doesn't work, I can offer to look at the project if you send it to info@scandit.com.

**Comment by hbi99** [comment]
Why don't you offer a repo, exemplifying a working test app?It feels like the way you're suggesting might take long time and doesn't prevent others from experiencing the exact same issue. With a test-repo, everyone can contribute to a solid version and issues can be tracked revolving that certain app.

**Comment by moritz-scandit** [comment]
The way we suggest to do it (through the CLI and with very small sample javascript) is very fast, it literally takes less than 2 minutes to do this while always building the project according to the Cordova version that you are currently using. A repo of an example app would be a lot more work as Cordova evolves and project structures can change.

I also can't see how such an example project would help you any further in this case as you will have to add the plugin to your own project no matter what and the easiest way is through the CLI. An example project will not help you with this. Please also be aware that this is not an issue with our plugin it is an issue with Cordova itself (or the individual setup of a person) where we have no interest in tracking issues as it is not our code and we can therefore not change anything about it. The way we describe how to create a sample app is the way it should be done according to Cordova and the way it has always worked for us and our customers (with the exception of a few which you will then see here). We are always here to try and help in that case and as I have offered multiple times already in this thread will look at projects that are sent to us.

**Comment by hbi99** [comment]
It is weird that you have closed this issue. People experienced the same problem but you think it is ok and think that it's their problem. No wonder that this repo does not get more stars. Hmm...
