### ISSUE TITLE
Swift version for barcode scanner plugin.

### ISSUE THREAD

**Issue by datomnurdin** [Scandit/BarcodeScannerPlugin#23]
Is it possible scandit provide swift version for this plugin?

**Comment by moritz-scandit** [comment]
What would be the use of providing it in Swift? As far as I can see the Cordova plugin classes are all still in Objective C and to write the plugin in Swift you would have to bridge to those classes which seems like an unnecessary hassle.

**Comment by datomnurdin** [comment]
Noted.
