### ISSUE TITLE
plugin not working with ionic

### ISSUE THREAD

**Issue by sandeepkacha** [Scandit/BarcodeScannerPlugin#24]
i am getting following errros when trying to build for android, ionic currently is built for android target api 21. Please look into the issue, Thanks.

BUILD FAILED
c:\Users\sandeep\Downloads\adt-bundle-windows-x86_64-20140321\adt-bundle-windows
-x86_64-20140321\sdk\tools\ant\build.xml:653: The following error occurred while
 executing this line:
c:\Users\sandeep\Downloads\adt-bundle-windows-x86_64-20140321\adt-bundle-windows
-x86_64-20140321\sdk\tools\ant\build.xml:698: null returned: 1

Total time: 4 seconds

c:\Users\sandeep\pemba\retail\platforms\android\cordova\node_modules\q\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s /c "ant debug -f c:\Users\sandeep\pe
mba\retail\platforms\android\build.xml -Dout.dir=ant-build -Dgen.absolute.dir=an
t-gen"
ERROR building one of the platforms: Error: c:\Users\sandeep\pemba\retail\platfo
rms\android\cordova\build.bat: Command failed with exit code 8
You may not have the required environment or OS to build this project
Error: c:\Users\sandeep\pemba\retail\platforms\android\cordova\build.bat: Comman
d failed with exit code 8
    at ChildProcess.whenDone (c:\Users\sandeep\AppData\Roaming\npm\node_modules\
cordova\node_modules\cordova-lib\src\cordova\superspawn.js:131:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)

**Comment by moritz-scandit** [comment]
Hi,

I can't see any reference specifically to our module. It looks to me like PhoneGap is failing internally somehow which is something we can't help with. I would advise you to try running the app by opening the project in an Android IDE instead of starting it through the console, this has solved many problems before. If that does not change anything I would recreate the project and try it again.

**Comment by sandeepkacha** [comment]
sorry for the trouble mortiz, mistake is on my side . Its due to cordova barcode scanner plugin installed. Thanks for prompt reply.
