### ISSUE TITLE
switch camera button not showing up on Android devices

### ISSUE THREAD

**Issue by dafi87** [Scandit/BarcodeScannerPlugin#25]
While experimenting with the cordova plugin it turned out that the switch camera button is not showing up on Android devices.

Plugin is called by
```
cordova.exec(scan_success, scan_failure, "ScanditSDK", "scan",
    ["XXXXXXXX",
      {"vibrate": true,
        "1DScanning" : false,
        "2DScanning" : false,
        "qr" : true,
        "force2dRecognition" : true,
        "inverseRecognition" : true,
        "cameraSwitchVisibility" : "always",
        "searchBar" : false,
        "torch" : true
      }
    ]);
```
The button shows up fine on an iPhone 5 using the same code. Tested on a LG G2 and Moto G (both have a second camera).

Thanks in advance for looking into it.

**Comment by moritz-scandit** [comment]
Hi,

I just tested this on Moto M and a Nexus 4 (we don't have an LG G2 here) and on both the button showed up and worked as expected. Please make sure that the resources used for the button are actually in your project's res/raw folder: camera_swap_icon.png and camera_swap_icon_pressed.png

**Comment by dafi87** [comment]
You are correct, those files were missing from res/raw on my android platform folder. Unfortunately I can't say why. After moving them manually, the plugin works like a charm. 
Thanks for your quick help!
