### ISSUE TITLE
continuousMode in android

### ISSUE THREAD

**Issue by balasaheb143** [Scandit/BarcodeScannerPlugin#26]
continuousMode for capure multiple barcode in android

**Comment by moritz-scandit** [comment]
Hi,

Multiple barcode support for Phonegap will eventually come but there is no timetable for it currently. If you do know some Java/Android you should be able to edit the plugin to do this at least for your specific case without a lot of changes.

**Comment by balasaheb143** [comment]
hi can you send sample code

On Tue, Jul 7, 2015 at 2:46 PM, moritz-scandit <notifications@github.com>
wrote:

> Hi,
>
> Multiple barcode support for Phonegap will eventually come but there is no
> timetable for it currently. If you do know some Java/Android you should be
> able to edit the plugin to do this at least for your specific case without
> a lot of changes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Scandit/BarcodeScannerPlugin/issues/26#issuecomment-119134070>
> .
>



-- 
BALASAHEB

**Comment by moritz-scandit** [comment]
Have a look at maxNumCodesPerFrame (http://docs.scandit.com/classcom_1_1mirasense_1_1scanditsdk_1_1_scandit_s_d_k_scan_settings.html#a676fca0e384163d910d10ac72c569d34) and the multi scan example here: http://docs.scandit.com/android-new-in-4_3.html. That is basically how multi scanning is done in the scanner and you then have to properly return those results to java script, currently only one code is ever returned. What you could do is simply execute the callback for each of the codes or change it such that all codes are returned at once.
