### ISSUE TITLE
Crash bug

### ISSUE THREAD

**Issue by mschwartz** [Scandit/BarcodeScannerPlugin#27]
I'm using the 4.4.2 test SDK.

Application crashes after 5-6 successful scans.  The scanner is called in a loop to allow the user to scan multiple items rapidly.

![image](https://cloud.githubusercontent.com/assets/329637/8959922/3ad5d20c-35c2-11e5-9e76-93be2a8262b4.png)

**Comment by moritz-scandit** [comment]
Please try the 4.7 beta release for phonegap (available in your scandit account) as big parts of the plugin were changed with it, there will be no more fixes coming for 4.4.2. If you are experiencing a crash with 4.7 beta as well then please attach a screenshot of the crash and a code sample of how that loop looks like.
