### ISSUE TITLE
Can't find documentation on possible return values for codetype

### ISSUE THREAD

**Issue by mcbejn** [Scandit/BarcodeScannerPlugin#29]
Hi guys,

Sorry to start this here, but I couldn't find a better place. It is not really a software issue - all I need is just a list of all possible code types that the Cordova plugin can return (strings like EAN13 etc). I couldn't find it in the documentation, can anyone please help me out?

Thanks!

**Comment by moritz-scandit** [comment]
"EAN8", "EAN13", "UPC12", "UPCE", "CODE128", "GS1-128", "CODE39", "CODE93", "ITF", "MSI", "CODABAR", "GS1-DATABAR", "GS1-DATABAR-EXPANDED", "QR", "GS1-QR", "DATAMATRIX", "GS1-DATAMATRIX", "PDF417", "TWO-DIGIT-ADD-ON", "FIVE-DIGIT-ADD-ON", "AZTEC"

I will update the documentation to reflect this.

**Comment by mcbejn** [comment]
Big thanks Moritz!

Cheers!
