### ISSUE TITLE
How to disable "Scanalytics"?

### ISSUE THREAD

**Issue by lucasfeliciano** [Scandit/BarcodeScannerPlugin#30]
I'm wondering if there is any option that i can pass when I'm initialising to disable 'Scanalytics".
Didn't find anything about this on the docs.
I just read in the "IT Security Overview SDK" that I'm able to do that but there is nothing explaining how.

**Comment by moritz-scandit** [comment]
There is no option to disable Scanalytics. Certain licenses give the option between two different libraries, one with scanalytics, one without. Not all licenses provide this option though.
