### ISSUE TITLE
remove view finder and logo

### ISSUE THREAD

**Issue by lucasfeliciano** [Scandit/BarcodeScannerPlugin#32]
Hello,

My company has a `consumer` license for both ios and android and for design issues we need to remove the view finder square because of design issues.

I tried to set:
    "viewfinderSize" : "0/0/0/0"
    "logoOffsets": "1000,0,1000,000"

But I still have a white dot in the center of the screen ( view fiender with size 0 ) and the logo.

**Edit:**

**I set the viewFinderSize to "3000/3000/3000/3000" so I was able to hide the viewfinder with the logo but only in iOS on android it doesnt make any difference.**

What is the best approach to do so?

**Comment by iciar-scandit** [comment]
We have already added a function to show/hide the viewfinder
