### ISSUE TITLE
Project doesnt build after update to xcode 7

### ISSUE THREAD

**Issue by lucasfeliciano** [Scandit/BarcodeScannerPlugin#33]
I'm receiving this error when I try to build the project:

ld:

 `
'MyProject/Plugins/com.mirasense.scanditsdk.plugin/ScanditBarcodeScanner.framework/ScanditBarcodeScanner(ScanditSDKBarcodePicker.o)' does not contain bitcode. 
You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64`
`

My project it is with bitcode enable already.

**Comment by iciar-scandit** [comment]
We have identified a problem with latest version of Xcode (Xcode 7); it uses by default a new intermediate representation during the build process that is optional but enabled by default and that we do not yet support. 

You can avoid the issue by disabling bitcode by setting the corresponding property:

e.g. in the .xcodeproj file itself setting ENABLE_BITCODE to "No" (ENABLE_BITCODE = NO).

We will release a 4.8.1 bug fix release later this week to address the issue.

**Comment by dotnetwise** [comment]
still nothing about this?

**Comment by moritz-scandit** [comment]
This issue has been resolved with 4.8.1 as Iciar wrote in the above post. The libraries are now built with bitcode included and there is no need to turn off bitcode anymore.
