### ISSUE TITLE
Plugin killing app on orientation change (Android)

### ISSUE THREAD

**Issue by mcbejn** [Scandit/BarcodeScannerPlugin#34]
Hi guys,

I am having an issue with my app on Android where everything works fine except when I change orientation of the phone to landscape - the app just breaks. Tested this on a few different phones, so it's not a particular system/phone.

My app has orientation locked to portrait with using the 
```
<preference name="orientation" value="portrait" />
```
in config.xml of the Cordova (Ionic) project. I've also tried with the ScreenOrientation plugin but no difference.

Any ideas on how I could solve this?

Plugin version is 4.7.0

Thanks in advance :)

**Comment by floerkem** [comment]
Hi, 

we will need to look into this. We started at a support ticket and will get back to you. 

Christian 
Scandit Support

**Comment by mcbejn** [comment]
Hi floerkem,

Just tried one more time on a blank project and the issue does not appear with version 4.8.0. 
4.7.0 still didn't work. 

It works for me though, so no need to spend too much time on this because of me :)

Thanks!

**Comment by kristianhristov** [comment]
Hello,

I'm experiencing a similar issue with the only difference that for me the orientation is fixed to Landscape and I use the landscapeMargins parameter, and every time I try to start the scanner the app breaks.

If I remove the landscapeMargins parameter the scanner starts but it starts in full screen.

I'm using version 4.8.1.

I'd appreciate your help.

Thanks!

**Comment by moritz-scandit** [comment]
Hi,

This is an issue that was fixed on August 19 and contained in the 4.7.2 release. Please always make sure that you are using the most recent version as the bug that you experience might already be fixed.
