### ISSUE TITLE
Extend support to Windows 8.1 Phone

### ISSUE THREAD

**Issue by bhack** [Scandit/BarcodeScannerPlugin#35]
Please extend this plugin to cover Windows 8.1 phone now that [SDK 4.8 support it](http://www.scandit.com/2015/09/24/scandit-barcode-scanner-sdk-version-4-8-released/).

**Comment by swenner** [comment]
Windows 8.1 support is available in the latest release (4.12.0). The binaries can be downloaded from scandit.com.
