### ISSUE TITLE
Error in Framework code in IOS

### ISSUE THREAD

**Issue by nap-patague** [Scandit/BarcodeScannerPlugin#36]
Hi

i downloaded the plugin using my account and extract on the desktop, when i add the plugins on our app, the code from the plugins framework has some error the build cannot proceed with it. i attached the screenshot. i'm using xcode 6.3.2

Thanks

Nap
![screen shot 2015-12-28 at 2 00 33 pm](https://cloud.githubusercontent.com/assets/2161053/12014668/8d9625de-ad6b-11e5-8780-484fc80c568f.png)
![screen shot 2015-12-28 at 2 00 46 pm](https://cloud.githubusercontent.com/assets/2161053/12014669/8dd4532c-ad6b-11e5-9e24-381e2d803f67.png)

**Comment by moritz-scandit** [comment]
You are seeing these errors because we are using Xcode 7 nonnull and nullable syntax and you are still on Xcode 6, please update to Xcode 7 to fix this.

**Comment by nap-patague** [comment]
Hi moritz,

thanks i will try your suggestion, i will update the xcode today and will close the ticket when the error is gone.

Thanks
Nap

**Comment by nap-patague** [comment]
Hi,

i updated the xcode to 7.2 and the plugin and our app is now working.. thanks

Nap
