### ISSUE TITLE
Add Windows Universal Support

### ISSUE THREAD

**Issue by SunboX** [Scandit/BarcodeScannerPlugin#37]
Please add support for Windows Universal Apps (Windows 10 / Windows 10 Mobile).

**Comment by moritz-scandit** [comment]
We are working on the plugin for Windows currently but there is no release date yet. You can expect it to be available in the 4.12 or 4.13 release.

**Comment by SunboX** [comment]
thx again! :smirk:

**Comment by swenner** [comment]
Windows Universal Support is available in the latest release (4.12.0). The binaries can be downloaded from scandit.com.
