### ISSUE TITLE
Add some way to check if the SDK is installed

### ISSUE THREAD

**Issue by SunboX** [Scandit/BarcodeScannerPlugin#38]
By now, we automatically build some apps and check if the (Phonegap) Scanner Plugin is available like this:

```js
if (
    'cordova' in window &&
    'plugins' in cordova &&
    'barcodeScanner' in cordova.plugins
    ) {
    this.scannerIsAvailable = true;
}
```

Because this plugin is using `cordova.exec`, we can't do this simple check for availability. Please provide some way to check if the plugin is installed or not at run time.

**Comment by moritz-scandit** [comment]
4.11 adds a javascript wrapper which means you will be able to just call if ('Scandit' in window) to check for the plugin. It will be released today or tomorrow.

**Comment by SunboX** [comment]
thx! :smiley:
