### ISSUE TITLE
Question: Scandit as a instance of UIView

### ISSUE THREAD

**Issue by lucasfeliciano** [Scandit/BarcodeScannerPlugin#42]
Hello there,

I'm wraping the scandit SDK into a react-native component but I'm having some problems to do so.

React-native API requires an UIView to be rendered into his own UIViewController and `SBSBarcodePicker` is a subclass of UIViewController which is not what I need.

Since I'm not a iOS developer I'm struggling to make it work.

What I tried to do was, create a UIViewController to setup my scandit intance:

```objectivec
#import "RCTScandit.h"
#import <ScanditBarcodeScanner/ScanditBarcodeScanner.h>
@implementation RCTScandit

/*
// Only override drawRect: if you perform custom drawing.
// An empty implementation adversely affects performance during animation.
*/

-(void)viewDidLoad {
  [super viewDidLoad];
  
  [self overlayAsView];

}

- (void)barcodePicker:(SBSBarcodePicker *)picker didScan:(SBSScanSession *)session {
  NSArray* recognized = session.newlyRecognizedCodes;
  SBSCode *code = [recognized firstObject];
  // add your own code to handle the barcode result e.g.
  NSLog(@"scanned %ld barcode: %@", (long)code.symbology, code.data);
}

- (void)overlayAsView {
  
  SBSScanSettings* scanSettings = [SBSScanSettings defaultSettings];
  scanSettings.cameraFacingPreference = SBSCameraFacingDirectionBack;
  [scanSettings setSymbology:SBSSymbologyEAN13 enabled:YES];
  [scanSettings setSymbology:SBSSymbologyUPC12 enabled:YES];
  [scanSettings setSymbology:SBSSymbologyQR enabled:YES];

  self.picker = [[SBSBarcodePicker alloc] initWithSettings:scanSettings];
  self.picker.scanDelegate = self;
  
  [self addChildViewController:self.picker];
  [self.view addSubview:self.picker.view];
  [self.picker didMoveToParentViewController:self];
  
  [self.picker startScanning];

}
@end
```

and then into my react-native module return just a view from that UIViewController:

```objectivec
//
//  RCTScanditManager.m
//  RCTScandit
//
//  Created by Lucas Feliciano on 07/02/16.
//

#import "RCTScanditManager.h"
#import "RCTScandit.h"

@implementation RCTScanditManager
RCT_EXPORT_MODULE();

- (UIView *)view
{
  RCTScandit *scandit = [[RCTScandit alloc] init];
  return scandit.view;
}


@end
```

But doing that I get a black screen with the white rectangle from scandit, I receive the prompt asking for camera permission but doesnt show a camera.

I might be wrong but look like that when I return the view from my UIViewController I'm returning only the top layer ( the white rectangle), there is a way to return only the camera?

My idea is when I make this module make it opensource ( without the scandit SDK of course ) so after that you could maintain it and have a module for react-native as well.
But I need your help for that :P

**Comment by moritz-scandit** [comment]
Hi Lucas,

As far as I can see you are doing everything correctly. Through picker.view you will get the entire view of the picker which includes the camera feed and the overlay so what you are seeing is not only the overlay. The camera just does not seem to be running. I am not really sure why that is, I quickly added your RCTScandit class in a native iOS app and added it as a subview, it displayed the running camera as expected.

Generally a black screen with the viewfinder visible would mean that you did not call startScanning and therefore did not start the camera, but clearly that is not the case. Have you tried scanning codes even though you did not see the camera? Maybe for some odd reason the preview is not showing but the camera is actually running. Another suggestion would be to delay the startScanning call by a bit and see whether that changes something (something like  [self.picker performSelector:@selector(startScanning) withObject:nil afterDelay:2.0])

**Comment by kaphacius** [comment]
Hi Lucas,

Are you sure that the `view` property you are returning has a proper frame? `alloc] init]` for creating a UIViewController is really not a common thing to do, I wonder if the view's size is set properly.

**Comment by moritz-scandit** [comment]
alloc] init] for a view controller is perfectly fine. Of course you will then have to adjust the frame or more likely add constraints to the view but there is no state where a view is missing a  proper frame, it would be very strange if this was possible. The fact that the scanner is visible etc. indicates that the view was properly added and its frame has been adjusted to make the content visible.

**Comment by lucasfeliciano** [comment]
Hello guys, 

I sorry for the delay.

I tried a couple of things:

1. Scan a barcode even if the camera was not being rendered.
2. tried to delay the `startScanning` method in the objective-c code.
3. I tried to expose that method to the javascript and delay it execution through the javascript bridge.

No success in all of the cases.

I even opened a ticket into the react-native repository to get some help, and they gave me some suggestions which is use a `UIView` to control the Scandit `UIViewControler` but since I'm not a iOS developer I'm still looking some codes and trying to understand how I can do it.

Here is the issue for reference: 
- https://github.com/facebook/react-native/issues/5807

**Comment by moritz-scandit** [comment]
What the react guys pointed out is very likely the problem, the UIViewController is simply deallocated as soon as the view is returned. You can copy their updated code for RCTScandit.m (there seems to be a typo in the layoutSubviews function but should be simple to fix) and simply change the RCTScandit.h file to not inherit from UIViewController but from UIView. In RCTScanditManager you then return scandit instead of scandit.view.

**Comment by lucasfeliciano** [comment]
Yeah, they just replied the issue there.

I'm working on it right now :)

I'll come with a feedback in a few minutes. 

Fingers crossed.

**Comment by lucasfeliciano** [comment]
I make those changes and now the view is white but in the other hand it is handling the scan.

I can put a barcode in front of it and it is logging into the console.

I'll keep debugging here to try to figure it out what is going on, but if you have anything in mind let me know :)

**Comment by lucasfeliciano** [comment]
Maybe because the frame is `0 0`?
<RCTScandit: 0x1366de9d0; frame = (0 0; 0 0); layer = <CALayer: 0x1366deb50>>`

**Comment by moritz-scandit** [comment]
Yes, it sounds like the problem now is that the view has a zero frame. You can initialize it differently with initWithFrame:CGRectMake(0, 0, width, height), however, I would assume that react would set the frame when you have to return a view or there is some property that you can read out that should tell you how big the view is. Something like that, but clearly React should be handling the resizing of the view.

**Comment by kaphacius** [comment]
That is actually what I suggested :)
You can try to set autolayout constraints for the view so it would have the proper frame

**Comment by moritz-scandit** [comment]
Yes, but this was not the problem before, before the view was visible. I would expect React to set constraints for the view as it should know how the module needs to be integrated in the bigger picture, so it would be weird that the module itself has to set constraints to fit into a view hierarchy that it knows nothing about. But as I said, I do not know how React handels this.

**Comment by lucasfeliciano** [comment]
Yeah, I'm not calling the initWithFrame method.

But to do so I need to pass a instance of CGRect with some values,
which values should I pass to create the rect?

**Comment by moritz-scandit** [comment]
You could for example set it to the screen size:

`CGRect screenRect = [[UIScreen mainScreen] bounds];
CGFloat screenWidth = screenRect.size.width;
CGFloat screenHeight = screenRect.size.height;`

It doesn't make much sense to me that you would have to do this. I would ask the React guys or check out other GUI modules what they do with their views. Maybe you have to expose properties where the user can set the width and height themselves.

**Comment by lucasfeliciano** [comment]
yeah, make sense but I need to call the the `initWithFrame` method, right?

`RCTScandit *scandit = [[RCTScandit alloc] initWithFrame:CGRect];`

Like this, and probably create the CGRect with the size of my screen, right?

How can I get this values from the `RCTScanditManager.m`

This are the headers that I'm importing

```objective-c
#import "RCTBridge.h"
#import "RCTViewManager.h"
#import "RCTScandit.h"
```

**Comment by moritz-scandit** [comment]
You might have to import UIKit

`#import <UIKit/UIKit.h>`

And then set it up like:
```
CGRect screenRect = [[UIScreen mainScreen] bounds];
RCTScandit *scandit = [[RCTScandit alloc] initWithFrame:screenRect];
```

**Comment by lucasfeliciano** [comment]
Sorry, I made the comment in the wrong issue :P

But Thanks anyway, into the RCTVIewManager I have the UIKit, so I probably can do that.

I'll try

**Comment by lucasfeliciano** [comment]
Alright, so now it is not more white.
I have the viewfinder in a blackscreen again but at least the scan callback it is been called, just the camera that is not been rendered but it is working

![img_0792](https://cloud.githubusercontent.com/assets/968014/13224367/805a3c22-d988-11e5-88cc-1db4eaca90bd.PNG)

**Comment by lucasfeliciano** [comment]
I manage to make it work. :)

Next step, implement the properties of the scanner and expose the methods to the javascript.
:)

**Comment by kmvkrish** [comment]
> Hello there,
> 
> I'm wraping the scandit SDK into a react-native component but I'm having some problems to do so.
> 
> React-native API requires an UIView to be rendered into his own UIViewController and `SBSBarcodePicker` is a subclass of UIViewController which is not what I need.
> 
> Since I'm not a iOS developer I'm struggling to make it work.
> 
> What I tried to do was, create a UIViewController to setup my scandit intance:
> 
> ```objc
> #import "RCTScandit.h"
> #import <ScanditBarcodeScanner/ScanditBarcodeScanner.h>
> @implementation RCTScandit
> 
> /*
> // Only override drawRect: if you perform custom drawing.
> // An empty implementation adversely affects performance during animation.
> */
> 
> -(void)viewDidLoad {
>   [super viewDidLoad];
> 
>   [self overlayAsView];
> 
> }
> 
> - (void)barcodePicker:(SBSBarcodePicker *)picker didScan:(SBSScanSession *)session {
>   NSArray* recognized = session.newlyRecognizedCodes;
>   SBSCode *code = [recognized firstObject];
>   // add your own code to handle the barcode result e.g.
>   NSLog(@"scanned %ld barcode: %@", (long)code.symbology, code.data);
> }
> 
> - (void)overlayAsView {
> 
>   SBSScanSettings* scanSettings = [SBSScanSettings defaultSettings];
>   scanSettings.cameraFacingPreference = SBSCameraFacingDirectionBack;
>   [scanSettings setSymbology:SBSSymbologyEAN13 enabled:YES];
>   [scanSettings setSymbology:SBSSymbologyUPC12 enabled:YES];
>   [scanSettings setSymbology:SBSSymbologyQR enabled:YES];
> 
>   self.picker = [[SBSBarcodePicker alloc] initWithSettings:scanSettings];
>   self.picker.scanDelegate = self;
> 
>   [self addChildViewController:self.picker];
>   [self.view addSubview:self.picker.view];
>   [self.picker didMoveToParentViewController:self];
> 
>   [self.picker startScanning];
> 
> }
> @end
> ```
> 
> and then into my react-native module return just a view from that UIViewController:
> 
> ```objc
> //
> //  RCTScanditManager.m
> //  RCTScandit
> //
> //  Created by Lucas Feliciano on 07/02/16.
> //
> 
> #import "RCTScanditManager.h"
> #import "RCTScandit.h"
> 
> @implementation RCTScanditManager
> RCT_EXPORT_MODULE();
> 
> - (UIView *)view
> {
>   RCTScandit *scandit = [[RCTScandit alloc] init];
>   return scandit.view;
> }
> 
> 
> @end
> ```
> 
> But doing that I get a black screen with the white rectangle from scandit, I receive the prompt asking for camera permission but doesnt show a camera.
> 
> I might be wrong but look like that when I return the view from my UIViewController I'm returning only the top layer ( the white rectangle), there is a way to return only the camera?
> 
> My idea is when I make this module make it opensource ( without the scandit SDK of course ) so after that you could maintain it and have a module for react-native as well.
> But I need your help for that :P

I am working with one of the Face Recognition iOS SDK for a React Native app. What the sdk provided is a class that obtains the RootViewController from the app Window, and presents another UIViewController on the RootViewController. Due to this, the approach you followed is not helping me to achieve loading the camera view into RCTViewManager handled ui.

Can you help me on this?

**Comment by lucatorella** [comment]
Hi @kmvkrish, did you try using our React Native SDK? It's here https://github.com/Scandit/barcodescanner-sdk-react-native

**Comment by kmvkrish** [comment]
> Hi @kmvkrish, did you try using our React Native SDK? It's here https://github.com/Scandit/barcodescanner-sdk-react-native

Hi @lucatorella , the face recognition SDK was not exposed as React-Native SDK. Instead it is a native iOS SDK. You can find it here [Ver ID iOS](https://github.com/AppliedRecognition/Ver-ID-UI-iOS)

**Comment by lucatorella** [comment]
All right, I assumed you wanted to use Scandit SDK 🙂 It seems your problem is very similar to what we solved in our React Native plugin. We also have a subclass of UIViewController that is exposed by our native iOS SDK. I suggest having a look at our React Native project so that you see how we solved it.
