### ISSUE TITLE
Cannot resolve symbol

### ISSUE THREAD

**Issue by lucasfeliciano** [Scandit/BarcodeScannerPlugin#49]
I'm trying to add the Scandit SDK to my react-native custom component.
I added the .aar file and already configured in my gradle file.

It is finding the classes and adding the import correctly but every method from the SDK I get `cannot resolve symbom 'nameOfMethod'`

![screen shot 2016-03-01 at 11 56 20](https://cloud.githubusercontent.com/assets/968014/13425111/0ab88b36-dfa5-11e5-8475-201f1d7fea46.png)

**Comment by biasmv** [comment]
Weird, it is somehow able to resolve the packages and class names.  Can you show the part of your gradle file where you add the dependency?

**Comment by lucasfeliciano** [comment]
Yeah, sure.
Here it is

```
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.facebook.react:react-native:0.20.+'
    compile(name:'ScanditBarcodeScanner', ext:'aar')
}

repositories {
    flatDir {
        dirs 'src/main/jniLibs'
    }
}
```

**Comment by biasmv** [comment]
OK, thanks.  Did you place the ScanditBarcodeScanner.aar file in src/main/jniLibs? If not, you will have to make sure that the directory containing the aar file is included in one of the repositories:

```
repositories {
      flatDir {
              dirs '/path/to/folder/containing/the/aar/file'
       }
 }
```

**Comment by biasmv** [comment]
I don't really know what's going on. Could you package your sample and send it to us? We will then check on our side.

**Comment by lucasfeliciano** [comment]
What do you need, exactly?

**Comment by biasmv** [comment]
thanks! You can send it to marco at scandit.com

**Comment by lucasfeliciano** [comment]
@biasmv done.

remember that you need to `npm install` before try to build it

**Comment by biasmv** [comment]
Should have seen this earlier. You are missing a method declaration. Like this it works:


```java
package com.rctscandit;

import android.content.Context;

import com.scandit.barcodepicker.BarcodePicker;
import com.scandit.barcodepicker.OnScanListener;
import com.scandit.barcodepicker.ScanSession;
import com.scandit.barcodepicker.ScanSettings;
import com.scandit.barcodepicker.ScanditLicense;
import com.scandit.recognition.Barcode;


public class RCTScanditView implements OnScanListener {
    RCTScanditView(Context context) {
        ScanditLicense.setAppKey("myKey");
        ScanSettings settings = ScanSettings.create();

        settings.setSymbologyEnabled(Barcode.SYMBOLOGY_EAN13, true);
        settings.setSymbologyEnabled(Barcode.SYMBOLOGY_UPCA, true);
        settings.setSymbologyEnabled(Barcode.SYMBOLOGY_QR, true);

        BarcodePicker picker = new BarcodePicker(context, settings);
        picker.setOnScanListener(this);
    }

    @Override
    public void didScan(ScanSession scanSession) {
        scanSession.getNewlyRecognizedCodes().get(0);
    }
}
```

**Comment by lucasfeliciano** [comment]
@biasmv yeah you are right.

Thanks!
Btw, I sent you an email.
Tell me what you think ;)

**Comment by lucasfeliciano** [comment]
This issue is solved.
Closing

**Comment by rastapasta** [comment]
@lucasfeliciano @biasmv would anyone of you mind sharing the mentioned React Native bridge with us for learning purposes? We got one up and running for iOS, but are struggling with with Android version :) Thanks + cheers!

**Comment by biasmv** [comment]
@rastapasta:  The work on the react native code has been done by @lucasfeliciano. If you have particular issues with your code, feel free to send them to support@scandit.com, including a description where you got stuck. We will then try to help you out.

Best,
Marco

**Comment by rastapasta** [comment]
@biasmv thanks for the reply - went along the learning curve and got it implemented pretty smoothly by myself 😄 :heart:

**Comment by biasmv** [comment]
Great, good to hear!
