### ISSUE TITLE
Android crash on rotation when no width/height set

### ISSUE THREAD

**Issue by Alex-Sessler** [Scandit/BarcodeScannerPlugin#55]
I am using release 4.13.1 to display a fullscreen with the following settings:

     Scandit.License.setAppKey(scanditKey);

      var settings = new Scandit.ScanSettings();
      settings.setSymbologyEnabled(Scandit.Barcode.Symbology.CODE39, true);
      settings.codeDuplicateFilter = -1;

      scanner = new Scandit.BarcodePicker(settings);
      scanner.beep = true;
      scanner.torch = true;
      scanner.vibrate = true;
      scanner.cameraSwitchVisibility = Scandit.ScanOverlay.CameraSwitchVisibility.NEVER;
      scanner.toolBarButtonCaption = "Cancel";
      scanner.searchBar = false;
      scanner.continuousMode = true;

When i rotate the device while the scanner is visible, the App crashes, which is caused by no height being set and null being returned by the portraitConstraints.getWidth(). This null is used in putInt() in ScanditSdk.java checkOrientation():

`constraints.putInt(PhonegapParamParser.paramWidth,
                mBarcodePicker.portraitConstraints.getWidth());`

**Comment by moritz-scandit** [comment]
Thank you for the bug report. I just looked into it and fixed it in the following commit: https://github.com/Scandit/BarcodeScannerPlugin/commit/4c6c396135e67450a01d3ccfed29999716d7fb8c
